export const Colors = {
  dark:     "#0F1117",
  green:    "#1D9E75",
  red:      "#E24B4A",
  amber:    "#EF9F27",
  muted:    "#94A3B8",
  border:   "#E8EDF2",
  surface:  "#F8F9FA",
  card:     "#FFFFFF",
  greenBg:  "#E6F4EE",
  redBg:    "#FCEBEB",
  amberBg:  "#FFF4E5",
  blue:     "#4A7AFF",
  blueBg:   "#EEF2FF",
  teal:     "#00B8D9",
  tealBg:   "#E5F8FC",
  pink:     "#FF6B9D",
  pinkBg:   "#FFF0F6",
  purple:   "#9B6BFF",
  purpleBg: "#F3EEFF",
} as const;
