import {
  pgTable,
  text,
  uuid,
  numeric,
  boolean,
  timestamp,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

// Clerk's user id (e.g. "user_2abc...") is the primary key — no separate
// internal id, since every foreign key in this schema needs to reference it.
export const users = pgTable("users", {
  id: text("id").primaryKey(),
  // Not present on the JWT payload we verify per-request; left null unless
  // populated later via a Clerk webhook or explicit profile fetch.
  email: text("email"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const wallets = pgTable("wallets", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  balance: numeric("balance", { mode: "number" }), // nullable: null = "not set"
  isDefault: boolean("is_default").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("wallets_user_id_idx").on(table.userId),
]);

export const categories = pgTable("categories", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  type: text("type", { enum: ["expense", "income"] }).notNull(),
  icon: text("icon").notNull(),
  parentId: uuid("parent_id"),
  isDefault: boolean("is_default").notNull().default(false),
}, (table) => [
  index("categories_user_id_idx").on(table.userId),
  // Case-insensitive: prevents "Groceries" and "groceries" coexisting under
  // the same type for the same user, not just byte-identical duplicates.
  uniqueIndex("categories_user_type_name_unique_idx").on(
    table.userId,
    table.type,
    sql`lower(${table.name})`
  ),
]);

// One row per user per month — a single aggregate spending limit covering
// all expense categories combined, not a per-category breakdown. The unique
// index enforces "at most one budget per user per month" at the DB level.
export const budgets = pgTable("budgets", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  limitAmount: numeric("limit_amount", { mode: "number" }).notNull(),
  month: text("month").notNull(), // "YYYY-MM"
  repeat: boolean("repeat").notNull().default(false),
}, (table) => [
  uniqueIndex("budgets_user_id_month_unique_idx").on(table.userId, table.month),
]);

// One row per linked messaging account. `channel` + `externalId` (the
// Telegram chat id) is unique so a chat can't be linked to two users at
// once; `userId` is not unique — left open for a future second channel
// (e.g. WhatsApp) linked alongside Telegram on the same account.
export const messagingLinks = pgTable("messaging_links", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  channel: text("channel", { enum: ["telegram"] }).notNull(),
  externalId: text("external_id").notNull(), // Telegram chat id
  externalDisplayName: text("external_display_name"), // Telegram username/first name, for display in Settings
  linkedAt: timestamp("linked_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("messaging_links_user_id_idx").on(table.userId),
  uniqueIndex("messaging_links_channel_external_id_unique_idx").on(table.channel, table.externalId),
]);

// Short-lived one-time codes generated by the app, consumed by the webhook
// when the user sends /start <code> to the bot. Expiry is enforced at query
// time (expiresAt < now), not by a cron sweep — dead rows are harmless and
// tiny in volume, so periodic cleanup isn't worth the added moving part.
export const messagingLinkCodes = pgTable("messaging_link_codes", {
  code: text("code").primaryKey(),
  userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  channel: text("channel", { enum: ["telegram"] }).notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// One row per delivered recap (weekly or monthly), for the in-app inbox and
// to make cron delivery idempotent — the unique index means a retried or
// double-fired cron run for the same user+period is a no-op insert, not a
// duplicate Telegram message. `message` is the phrased sentence actually
// sent; `data` is the raw computed JSON it was phrased from, kept so the
// inbox can re-render richer detail later without recomputing history.
export const recaps = pgTable("recaps", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  periodType: text("period_type", { enum: ["weekly", "monthly"] }).notNull(),
  periodStart: text("period_start").notNull(), // "YYYY-MM-DD"
  periodEnd: text("period_end").notNull(), // "YYYY-MM-DD"
  message: text("message").notNull(),
  data: text("data").notNull(), // JSON.stringify of the computed RecapData
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
}, (table) => [
  index("recaps_user_id_created_at_idx").on(table.userId, table.createdAt),
  uniqueIndex("recaps_user_period_unique_idx").on(table.userId, table.periodType, table.periodStart),
]);

export const transactions = pgTable("transactions", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }),
  merchant: text("merchant").notNull(),
  categoryId: uuid("category_id").notNull().references(() => categories.id, { onDelete: "restrict" }),
  walletId: uuid("wallet_id").references(() => wallets.id, { onDelete: "set null" }),
  txType: text("tx_type", { enum: ["inc", "exp"] }).notNull(),
  amount: numeric("amount", { mode: "number" }).notNull(),
  date: text("date").notNull(), // "YYYY-MM-DD"
  time: text("time").notNull(), // "10:22 AM"
  // Cloudinary public_id ("userId/uuid"), null when the transaction wasn't
  // created from a scanned receipt (e.g. manual entry).
  receiptKey: text("receipt_key"),
}, (table) => [
  index("transactions_user_id_date_idx").on(table.userId, table.date),
  index("transactions_category_id_idx").on(table.categoryId),
  index("transactions_wallet_id_idx").on(table.walletId),
]);
