import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useColorScheme as useNativewindColorScheme } from 'nativewind';
import * as SystemUI from 'expo-system-ui';

type Theme = 'light' | 'dark' | 'system';

interface ThemeContextType {
  theme: Theme;
  isDark: boolean;
  setTheme: (t: Theme) => void;
  /** False until the persisted preference has been read from AsyncStorage.
   *  Callers that render before this flips (e.g. the root layout deciding
   *  when to hide the splash screen) would otherwise show a frame in the
   *  wrong theme — system default — before snapping to the saved one. */
  hydrated: boolean;
}

const ThemeContext = createContext<ThemeContextType>({
  theme: 'system',
  isDark: false,
  setTheme: () => {},
  hydrated: false,
});

export function ThemeProvider({ children }: { children: React.ReactNode }) {
  // isDark is derived from NativeWind's OWN colorScheme observable (not React
  // Native's core useColorScheme + a separate nativewindColorScheme.set()
  // side effect) so it can never drift out of sync with `dark:` class
  // resolution. The two used to be independent subscriptions to appearance —
  // NativeWind's `set()` on native calls RN's Appearance.setColorScheme(),
  // which *itself* changes what RN's own useColorScheme() reports, creating
  // a feedback loop that could leave isDark (JS-driven colors) and NativeWind's
  // dark: variants disagreeing, especially around 'system' <-> explicit
  // transitions. Reading from the same observable NativeWind uses internally
  // guarantees agreement by construction.
  const { colorScheme, setColorScheme } = useNativewindColorScheme();
  const [theme, setThemeState] = useState<Theme>('system');
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem('app_theme')
      .then(saved => {
        if (saved === 'light' || saved === 'dark' || saved === 'system') {
          setThemeState(saved);
          setColorScheme(saved);
        }
      })
      // A rejected read (corrupt storage, first-run platform quirks) just
      // means falling back to the system theme — never let it become an
      // unhandled rejection, and never let it block `hydrated` below.
      .catch(e => console.warn('Failed to read saved theme', e))
      // Flips even with nothing saved (first launch) or a read failure —
      // otherwise a caller gating on `hydrated` (the splash screen) would
      // hang forever instead of just falling back to the system theme.
      .finally(() => setHydrated(true));
    // Only ever runs once on mount to hydrate the persisted preference.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Stable reference — won't cause context consumers to re-render on unrelated state changes
  const setTheme = useCallback((t: Theme) => {
    setThemeState(t);
    setColorScheme(t);
    AsyncStorage.setItem('app_theme', t);
  }, [setColorScheme]);

  const isDark = colorScheme === 'dark';

  // AppTheme (android/.../styles.xml, regenerated by expo prebuild — see
  // plugins/withAndroidBrandTheme.js) has no android:windowBackground set,
  // so the native Activity window itself defaults to AppCompat's light
  // background. That's a layer beneath everything React Native renders —
  // Stack's contentStyle only colors each screen's own RN view, not the
  // window underneath it — so during native push/pop compositing (and
  // worst on the trailing edge of a horizontal slide) a sliver of that light
  // window background could show through before the incoming screen's RN
  // content fully covers it. Setting it here keeps the native window itself
  // in sync with the app's actual (possibly explicitly-overridden, not just
  // system) theme — a static values-night resource can't do that, since
  // this app's theme can differ from the OS setting.
  useEffect(() => {
    SystemUI.setBackgroundColorAsync(isDark ? '#0b0f19' : '#f1f5f9').catch(() => {});
  }, [isDark]);

  // Only a new object when theme, isDark, or hydrated actually changes
  const value = useMemo<ThemeContextType>(
    () => ({ theme, isDark, setTheme, hydrated }),
    [theme, isDark, setTheme, hydrated],
  );

  return (
    <ThemeContext.Provider value={value}>
      {children}
    </ThemeContext.Provider>
  );
}

export const useTheme = () => useContext(ThemeContext);

export interface ThemeColors {
  /** Secondary/icon text — mutedFg token. */
  mutedFg: string;
  /** Borders, dividers, input outlines — border/input token. */
  border: string;
  /** Primary text — foreground token. */
  foreground: string;
  /** Muted surface backgrounds (icon containers, segmented-control tracks) — muted token. */
  muted: string;
  /** Card surface background — card token. */
  card: string;
  /** Success/income color — positive token. */
  positive: string;
  /** Error/expense color — negative token. */
  negative: string;
  /** Positive token at ~12% opacity, for icon-container backgrounds. */
  positiveMuted: string;
  /** Warning/reminder color — warning token. */
  warning: string;
}

// Resolved light/dark values for the tailwind.config.js tokens that don't
// have a className equivalent at these call sites (JS-driven color props on
// icons, Switch, inline style objects) — mirrors the *-dark suffix pairs in
// tailwind.config.js exactly, so a future palette change only needs editing
// here and there instead of every isDark ? '#..' : '#..' call site (see
// brandBlue() in constants/colors.ts for the established version of this
// pattern with a single value instead of five).
const LIGHT_COLORS: ThemeColors = {
  mutedFg: '#71717a',
  border: '#e4e4e7',
  foreground: '#09090b',
  muted: '#f4f4f5',
  card: '#ffffff',
  positive: '#16a34a',
  negative: '#dc2626',
  positiveMuted: 'rgba(22,163,74,0.12)',
  warning: '#d97706',
};

const DARK_COLORS: ThemeColors = {
  mutedFg: '#9ca3af',
  border: '#374151',
  foreground: '#fafafa',
  muted: '#242b3d',
  card: '#1a1f2e',
  positive: '#22c55e',
  negative: '#f87171',
  positiveMuted: 'rgba(34,197,94,0.12)',
  warning: '#fbbf24',
};

export function useThemeColors(): ThemeColors {
  const { isDark } = useTheme();
  return isDark ? DARK_COLORS : LIGHT_COLORS;
}
